#pragma once
#pragma comment(lib,"AppFrame.lib")

//#include <EffekseerForDXLib.h>
//#include <DxLib.h>
#include "Application/ApplicationBase.h"
#include "CFile/CFile.h"
#include "Component/Component.h"
#include "Easing/Easing.h"
#include "Effect/Effect.h"
#include "GamePad/XPad/GameXPad.h"
#include "Matrix3D/Matrix3D.h"
#include "Mode/ModeBase.h"
#include "Mode/ModeServer.h"
#include "MyMath/MyMath.h"
#include "Object/ObjectBase.h"
#include "Vector3D/Vector3D.h"
#include "Sound/SoundItem/SoundItemBase.h"
#include "Sound/SoundServer/SoundServer.h"
#include "ResourceManager/ResourceManager.h"
